version: '3'

# https://ridwanfajar.medium.com/send-your-container-logs-to-elk-elasticsearch-logstash-and-kibana-with-gelf-driver-7995714fbbad

services:

  elasticsearch:
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    image: elasticsearch:7.16.3
    networks:
      - elk
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:z

  logstash:
    command:
      - --config.string
      - >-
        input {
          gelf {
            port => 12201
          }
        }

        output {
          elasticsearch {
            hosts => ["elasticsearch:9200"]
            index => "logstash-%{+YYYY-MM-dd}"
          }
        }
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    image: logstash:7.16.3
    networks:
      - elk
    ports:
      - 9600:9600
      - 12201:12201/udp
    restart: always

  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
      - logstash
    image: kibana:7.16.3
    networks:
      - elk
    ports:
      - 5601:5601

  logger_1:
    container_name: logger-001
    environment:
      APPLICATION_ID: logger-001
    depends_on:
      - logstash
    image: dockter/mock-logging
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "logger-001"
    networks:
      - elk
    restart: always

  logger_2:
    container_name: logger-002
    environment:
      APPLICATION_ID: logger-002
    depends_on:
      - logstash
    image: dockter/mock-logging
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "logger-002"
    networks:
      - elk
    restart: always

networks:
  elk:

volumes:
  elasticsearch:
